#define stmt_dSP() dSP
#define stmt_dMARK() dMARK
#define stmt_dAX() dAX
#define stmt_dITEMS() dITEMS
#define stmt_SPAGAIN() SPAGAIN
#define stmt_ENTER() ENTER
#define stmt_SAVETMPS() SAVETMPS
#define stmt_PUTBACK() PUTBACK
#define stmt_FREETMPS() FREETMPS
#define stmt_LEAVE() LEAVE
#define stmt_XSprePUSH() XSprePUSH
